environmentConfig:
  environment: production
  rootFolder: /home/ykato/Documents/bvpixel/
  outputPath: /home/ykato/Documents/clients/
  fileNamePattern: PPConversion
  timeInterval: 1
  healthCheckConectionUrl: https://www.pravda.com.ua/
mongoConfig:
  host: localhost
  port: 27017
  database: jobdb
server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001